spring:
  application:
    name: students-api
  data:
    mongodb:
      database: '${MONGO_DB}'
        host: '${MONGO_HOST}'
        port: 27017
        username: '${MONGO_USERNAME}'
        password: '${MONGO_PASSWORD}'
        #authentication-database: admin
  management:
    endpoint:
      metrics:
        enabled: true
      loggers:
        enabled: true
      health:
        enabled: true
      info:
        enabled: true